homePage:
    path: /
    controller: App\Controller\HomeController::index
login:
    path: /login
    controller: App\Controller\SecurityController::login
controllers:
    resource: '../src/Controller/'
    type: annotation

